stages:
  - test
  - deploy

webapp:
  image: mhart/alpine-node:10
  stage: test
  script:
    - apk add bash git curl python --update-cache
    - npm i
    - echo "Pending tests :("
    - npm run build --production
    - npm prune --production
  artifacts:
    paths:
      - node_modules/
      - dist/app/
      - dist/img/
    expire_in: 1 hour
  variables:
    NODE_ENV: testing

docker:image:
  stage: deploy
  image: docker:1.12
  services:
    - docker:dind
  script:
    - docker version
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    # push only for tags
    - "[[ -z $CI_BUILD_TAG ]] && exit 0"
    - export DOCKER_IMAGE_TAG=$(echo $CI_BUILD_TAG | awk '{ print substr($1,2)}')
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
